version: "3.7"
services:

  intranet:
    image: serenup.intranet:v1.0
    container_name: intranet
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      dockernetwork:
        ipv4_address: 172.18.0.104

networks:
  dockernetwork:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
