version: "3.7"
services:

  shopapi:
    image: serenup.shopapi:v1.0
    container_name: shopapi
    restart: unless-stopped
    ports:
      - 8083:80
    networks:
      dockernetwork:
        ipv4_address: 172.18.0.103

networks:
  dockernetwork:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
